### ISSUE TITLE
Installation problem:

### ISSUE THREAD

**Issue by ElvarisGjinali** [sseffa/sf_cms#20]
I try to install and I think composer try to install some L5 packgages:

 Problem 1
    - Installation request for davejamesmiller/laravel-breadcrumbs dev-master -> satisfiable by davejamesmiller/laravel-breadcrumbs[dev-master].
    - Conclusion: don't install laravel/framework v4.2.17
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.1
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.10
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.11
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.12
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.13
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.14
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.15
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.16
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.2
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.3
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.4
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.5
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.6
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.7
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.8
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.9
    - davejamesmiller/laravel-breadcrumbs dev-master requires illuminate/support 5.* -> satisfiable by illuminate/support[v5.0.0, v5.0.4].
    - Conclusion: don't install illuminate/support v5.0.4
    - Installation request for laravel/framework 4.2.* -> satisfiable by laravel/framework[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.1
7, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by stojankukrika** [comment]
What package you tray to install?

**Comment by ElvarisGjinali** [comment]
I am trying to make the first installation, only those packages that holds composer !?!
